
#define MICROPY_HW_BOARD_NAME "PyCubedMini"
#define MICROPY_HW_MCU_NAME "samd51G19"
#define CIRCUITPY_MCU_FAMILY samd51

#define MICROPY_HW_NEOPIXEL   (&pin_PB22)

#define MICROPY_PORT_A        (0)
#define MICROPY_PORT_B        (0)
#define MICROPY_PORT_C        (0)
#define MICROPY_PORT_D 		  (0)

#define CALIBRATE_CRYSTALLESS (0)
#define CIRCUITPY_INTERNAL_NVM_SIZE 1024
#define CIRCUITPY_INTERNAL_FLASH_FILESYSTEM_SIZE (128*1024)

// #define BOARD_FLASH_SIZE (FLASH_SIZE - 0x4000 - 0x0100000)

#define DEFAULT_I2C_BUS_SCL  (&pin_PA16)
#define DEFAULT_I2C_BUS_SDA  (&pin_PA17)

#define DEFAULT_SPI_BUS_SCK  (&pin_PA09)
#define DEFAULT_SPI_BUS_MOSI (&pin_PA08)
#define DEFAULT_SPI_BUS_MISO (&pin_PA10)

#define IGNORE_PIN_PA24     1
#define IGNORE_PIN_PA25     1
